name: CI Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.build_step.outputs.artifact_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check app version
        run: echo "App version = $(cat version.txt)"

      - name: Build application
        id: build_step
        run: |
          VERSION=$(cat version.txt)
          ARTIFACT_NAME="artifact_${VERSION}"
          zip -r "scripts/${ARTIFACT_NAME}.zip" scripts/
          echo "artifact_name=${ARTIFACT_NAME}" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: scripts/*.zip
          name: ${{ steps.build_step.outputs.artifact_name }}
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ needs.build.outputs.artifact_name }}
            path: artifacts/
        - name: Extract artifact
          run: unzip artifacts/*.zip -d extracted
        - name: Install Postgresql
          run: |
            sudo apt-get update
            sudo apt-get install -y postgresql-client
        - name: 'Execute SQL'
          run: |
            export PGPASSWORD=demo_gha_2026
              psql -h "aws-1-eu-central-1.pooler.supabase.com" \
                -p 5432 \
                -d postgres \
                -U postgres.qxqpncxzbiuhsodhgmwk \
                -f extracted/scripts/dev.sql